[general]
import = [ "~/.config/alacritty/colors.toml" ]

[font]
# normal = { family = "UbuntuMono Nerd Font", style = "Regular" }
normal = { family = "JetBrainsMono Nerd Font", style = "Regular" }
size = 13

[window]
title = "Terminal"
# opacity = 0.8

# [colors.primary]
# background = "#000000"

[window.padding]
x = 3
y = 3

# [[keyboard.bindings]]
# key = "Space"
# mods = "Control|Alt"
# action = "ToggleViMode"

[[keyboard.bindings]]
key = "Escape"
mode = "Vi"
action = "ToggleViMode"


